application:
  host: 0.0.0.0
  port: 8006
  ssl: 8005
database:
  source: screen:Screen#2021@tcp(10.170.139.12:3306)/NOI_fund_screen?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
cache:
  redis: 10.170.139.12:6379
rpc:
  name: fund_screen
  host: localhost
  port: 50053
consul:
  host: 10.170.139.12
  port: 8500