// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.18.0
// source: classify.proto

package services

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClassifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secucode []string `protobuf:"bytes,1,rep,name=secucode,proto3" json:"secucode,omitempty"`
}

func (x *ClassifyReq) Reset() {
	*x = ClassifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyReq) ProtoMessage() {}

func (x *ClassifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_classify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyReq.ProtoReflect.Descriptor instead.
func (*ClassifyReq) Descriptor() ([]byte, []int) {
	return file_classify_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyReq) GetSecucode() []string {
	if x != nil {
		return x.Secucode
	}
	return nil
}

type ClassifyResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*Classify `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ClassifyResp) Reset() {
	*x = ClassifyResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResp) ProtoMessage() {}

func (x *ClassifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_classify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResp.ProtoReflect.Descriptor instead.
func (*ClassifyResp) Descriptor() ([]byte, []int) {
	return file_classify_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResp) GetData() []*Classify {
	if x != nil {
		return x.Data
	}
	return nil
}

type Classify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secucode string `protobuf:"bytes,1,opt,name=secucode,proto3" json:"secucode,omitempty"`
	First    string `protobuf:"bytes,2,opt,name=first,proto3" json:"first,omitempty"`
	Second   string `protobuf:"bytes,3,opt,name=second,proto3" json:"second,omitempty"`
}

func (x *Classify) Reset() {
	*x = Classify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_classify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Classify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Classify) ProtoMessage() {}

func (x *Classify) ProtoReflect() protoreflect.Message {
	mi := &file_classify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Classify.ProtoReflect.Descriptor instead.
func (*Classify) Descriptor() ([]byte, []int) {
	return file_classify_proto_rawDescGZIP(), []int{2}
}

func (x *Classify) GetSecucode() string {
	if x != nil {
		return x.Secucode
	}
	return ""
}

func (x *Classify) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *Classify) GetSecond() string {
	if x != nil {
		return x.Second
	}
	return ""
}

var File_classify_proto protoreflect.FileDescriptor

var file_classify_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x0b, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x63,
	0x75, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x63,
	0x75, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x54, 0x0a,
	0x08, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x63,
	0x75, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x63,
	0x75, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_classify_proto_rawDescOnce sync.Once
	file_classify_proto_rawDescData = file_classify_proto_rawDesc
)

func file_classify_proto_rawDescGZIP() []byte {
	file_classify_proto_rawDescOnce.Do(func() {
		file_classify_proto_rawDescData = protoimpl.X.CompressGZIP(file_classify_proto_rawDescData)
	})
	return file_classify_proto_rawDescData
}

var file_classify_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_classify_proto_goTypes = []interface{}{
	(*ClassifyReq)(nil),  // 0: services.ClassifyReq
	(*ClassifyResp)(nil), // 1: services.ClassifyResp
	(*Classify)(nil),     // 2: services.Classify
}
var file_classify_proto_depIdxs = []int32{
	2, // 0: services.ClassifyResp.data:type_name -> services.Classify
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_classify_proto_init() }
func file_classify_proto_init() {
	if File_classify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_classify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassifyResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_classify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Classify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_classify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_classify_proto_goTypes,
		DependencyIndexes: file_classify_proto_depIdxs,
		MessageInfos:      file_classify_proto_msgTypes,
	}.Build()
	File_classify_proto = out.File
	file_classify_proto_rawDesc = nil
	file_classify_proto_goTypes = nil
	file_classify_proto_depIdxs = nil
}
