// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.18.0
// source: style.proto

package services

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// many表示是否请求多期数据
type StyleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Funds []string `protobuf:"bytes,1,rep,name=funds,proto3" json:"funds,omitempty"`
	Many  bool     `protobuf:"varint,2,opt,name=many,proto3" json:"many,omitempty"`
}

func (x *StyleReq) Reset() {
	*x = StyleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_style_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StyleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StyleReq) ProtoMessage() {}

func (x *StyleReq) ProtoReflect() protoreflect.Message {
	mi := &file_style_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StyleReq.ProtoReflect.Descriptor instead.
func (*StyleReq) Descriptor() ([]byte, []int) {
	return file_style_proto_rawDescGZIP(), []int{0}
}

func (x *StyleReq) GetFunds() []string {
	if x != nil {
		return x.Funds
	}
	return nil
}

func (x *StyleReq) GetMany() bool {
	if x != nil {
		return x.Many
	}
	return false
}

type StyleResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data map[string]*Styles `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *StyleResp) Reset() {
	*x = StyleResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_style_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StyleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StyleResp) ProtoMessage() {}

func (x *StyleResp) ProtoReflect() protoreflect.Message {
	mi := &file_style_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StyleResp.ProtoReflect.Descriptor instead.
func (*StyleResp) Descriptor() ([]byte, []int) {
	return file_style_proto_rawDescGZIP(), []int{1}
}

func (x *StyleResp) GetData() map[string]*Styles {
	if x != nil {
		return x.Data
	}
	return nil
}

type Styles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Styles []*Styles_Style `protobuf:"bytes,1,rep,name=styles,proto3" json:"styles,omitempty"`
}

func (x *Styles) Reset() {
	*x = Styles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_style_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Styles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Styles) ProtoMessage() {}

func (x *Styles) ProtoReflect() protoreflect.Message {
	mi := &file_style_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Styles.ProtoReflect.Descriptor instead.
func (*Styles) Descriptor() ([]byte, []int) {
	return file_style_proto_rawDescGZIP(), []int{2}
}

func (x *Styles) GetStyles() []*Styles_Style {
	if x != nil {
		return x.Styles
	}
	return nil
}

type Styles_Style struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secucode string `protobuf:"bytes,1,opt,name=secucode,proto3" json:"secucode,omitempty"`
	Date     string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Style    string `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
}

func (x *Styles_Style) Reset() {
	*x = Styles_Style{}
	if protoimpl.UnsafeEnabled {
		mi := &file_style_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Styles_Style) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Styles_Style) ProtoMessage() {}

func (x *Styles_Style) ProtoReflect() protoreflect.Message {
	mi := &file_style_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Styles_Style.ProtoReflect.Descriptor instead.
func (*Styles_Style) Descriptor() ([]byte, []int) {
	return file_style_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Styles_Style) GetSecucode() string {
	if x != nil {
		return x.Secucode
	}
	return ""
}

func (x *Styles_Style) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Styles_Style) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

var File_style_proto protoreflect.FileDescriptor

var file_style_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x08, 0x53, 0x74, 0x79, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x66, 0x75, 0x6e, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x6e,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6d, 0x61, 0x6e, 0x79, 0x22, 0x89, 0x01,
	0x0a, 0x09, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x31, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x49,
	0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x73, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x87, 0x01, 0x0a, 0x06, 0x53, 0x74,
	0x79, 0x6c, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x53, 0x74, 0x79, 0x6c, 0x65, 0x73, 0x2e, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x52, 0x06, 0x73, 0x74,
	0x79, 0x6c, 0x65, 0x73, 0x1a, 0x4d, 0x0a, 0x05, 0x53, 0x74, 0x79, 0x6c, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x63, 0x75, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x63, 0x75, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x79, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x79, 0x6c, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_style_proto_rawDescOnce sync.Once
	file_style_proto_rawDescData = file_style_proto_rawDesc
)

func file_style_proto_rawDescGZIP() []byte {
	file_style_proto_rawDescOnce.Do(func() {
		file_style_proto_rawDescData = protoimpl.X.CompressGZIP(file_style_proto_rawDescData)
	})
	return file_style_proto_rawDescData
}

var file_style_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_style_proto_goTypes = []interface{}{
	(*StyleReq)(nil),     // 0: services.StyleReq
	(*StyleResp)(nil),    // 1: services.StyleResp
	(*Styles)(nil),       // 2: services.Styles
	nil,                  // 3: services.StyleResp.DataEntry
	(*Styles_Style)(nil), // 4: services.Styles.Style
}
var file_style_proto_depIdxs = []int32{
	3, // 0: services.StyleResp.data:type_name -> services.StyleResp.DataEntry
	4, // 1: services.Styles.styles:type_name -> services.Styles.Style
	2, // 2: services.StyleResp.DataEntry.value:type_name -> services.Styles
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_style_proto_init() }
func file_style_proto_init() {
	if File_style_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_style_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StyleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_style_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StyleResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_style_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Styles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_style_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Styles_Style); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_style_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_style_proto_goTypes,
		DependencyIndexes: file_style_proto_depIdxs,
		MessageInfos:      file_style_proto_msgTypes,
	}.Build()
	File_style_proto = out.File
	file_style_proto_rawDesc = nil
	file_style_proto_goTypes = nil
	file_style_proto_depIdxs = nil
}
